CREATE SCHEMA nyc_taxi;

ALTER USER postgres WITH PASSWORD 'SCRAM-SHA-256$4096:o/9kCdWmdcsoDgb6mQ8pHw==$q39j75o8VjhvqVzGbLpBPEbIZj55sRCGLZ0RO6cfLhk=:O/S78Qz6cb+0fNmmcO64YeZUh2xtpunA3k4+ZzjtzIg=';

CREATE ROLE reader NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN NOREPLICATION NOBYPASSRLS;
GRANT CONNECT ON DATABASE de_zoomcamp TO reader;
GRANT USAGE ON SCHEMA nyc_taxi TO reader;
GRANT SELECT ON ALL TABLES IN SCHEMA nyc_taxi TO reader;

CREATE USER fmerinocasallo WITH ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:jjoc29Ap7tyzZMhUrmgMhw==$oJmhjq9uzCAbtVu60zxO04kO4j/YJijIsUqlFR6MLAE=:PCNFwNojAdRnJblNkKNj8f3h3NRzLOLMrdbbpEwrYRk=';
GRANT reader TO fmerinocasallo;
